######################################################################
# Automatically generated by qmake (2.01a) Wed May 20 16:40:41 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += jpeg_org.c
